import type { Metadata } from "next";
import "../styles/globals.css";
import { calSemibold, geistMono, geistSans, inter, matter, robotoMono } from "../../public/fonts";
import { ToastProvider } from "@/components/ui/toast";
import Footer from "@/components/sections/Footer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${calSemibold.variable} ${matter.variable} ${inter.variable} ${robotoMono.variable} ${geistSans.variable} ${geistMono.variable} antialiased light`}
      >
        {/* don't use dark mode this website is light only if u want dark u will edit alot, sorry! */}
        <ToastProvider>
          {children}
          <Footer />
        </ToastProvider>
      </body>
    </html>
  );
}
